// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import (
	comment "be_medsos/features/comment"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// DeleteComment provides a mock function with given fields: commentID
func (_m *Repository) DeleteComment(commentID uint) error {
	ret := _m.Called(commentID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertComment provides a mock function with given fields: userID, postingID, newComment
func (_m *Repository) InsertComment(userID uint, postingID uint, newComment comment.Comment) (comment.Comment, error) {
	ret := _m.Called(userID, postingID, newComment)

	var r0 comment.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint, comment.Comment) (comment.Comment, error)); ok {
		return rf(userID, postingID, newComment)
	}
	if rf, ok := ret.Get(0).(func(uint, uint, comment.Comment) comment.Comment); ok {
		r0 = rf(userID, postingID, newComment)
	} else {
		r0 = ret.Get(0).(comment.Comment)
	}

	if rf, ok := ret.Get(1).(func(uint, uint, comment.Comment) error); ok {
		r1 = rf(userID, postingID, newComment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateComment provides a mock function with given fields: input
func (_m *Repository) UpdateComment(input comment.Comment) (comment.Comment, error) {
	ret := _m.Called(input)

	var r0 comment.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(comment.Comment) (comment.Comment, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(comment.Comment) comment.Comment); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(comment.Comment)
	}

	if rf, ok := ret.Get(1).(func(comment.Comment) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
