// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import (
	jwt "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"

	models "be_medsos/features/models"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AddPosting provides a mock function with given fields: token, newPosting
func (_m *Service) AddPosting(token *jwt.Token, newPosting models.Posting) (models.Posting, error) {
	ret := _m.Called(token, newPosting)

	var r0 models.Posting
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwt.Token, models.Posting) (models.Posting, error)); ok {
		return rf(token, newPosting)
	}
	if rf, ok := ret.Get(0).(func(*jwt.Token, models.Posting) models.Posting); ok {
		r0 = rf(token, newPosting)
	} else {
		r0 = ret.Get(0).(models.Posting)
	}

	if rf, ok := ret.Get(1).(func(*jwt.Token, models.Posting) error); ok {
		r1 = rf(token, newPosting)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOne provides a mock function with given fields: id
func (_m *Service) GetOne(id uint) (models.Posting, []models.Comment, error) {
	ret := _m.Called(id)

	var r0 models.Posting
	var r1 []models.Comment
	var r2 error
	if rf, ok := ret.Get(0).(func(uint) (models.Posting, []models.Comment, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) models.Posting); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Posting)
	}

	if rf, ok := ret.Get(1).(func(uint) []models.Comment); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]models.Comment)
		}
	}

	if rf, ok := ret.Get(2).(func(uint) error); ok {
		r2 = rf(id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// HapusPosting provides a mock function with given fields: token, postingID
func (_m *Service) HapusPosting(token *jwt.Token, postingID uint) error {
	ret := _m.Called(token, postingID)

	var r0 error
	if rf, ok := ret.Get(0).(func(*jwt.Token, uint) error); ok {
		r0 = rf(token, postingID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SemuaPosting provides a mock function with given fields: page, limit
func (_m *Service) SemuaPosting(page int, limit int) ([]models.Posting, error) {
	ret := _m.Called(page, limit)

	var r0 []models.Posting
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.Posting, error)); ok {
		return rf(page, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.Posting); ok {
		r0 = rf(page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Posting)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePosting provides a mock function with given fields: token, input
func (_m *Service) UpdatePosting(token *jwt.Token, input models.Posting) (models.Posting, error) {
	ret := _m.Called(token, input)

	var r0 models.Posting
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwt.Token, models.Posting) (models.Posting, error)); ok {
		return rf(token, input)
	}
	if rf, ok := ret.Get(0).(func(*jwt.Token, models.Posting) models.Posting); ok {
		r0 = rf(token, input)
	} else {
		r0 = ret.Get(0).(models.Posting)
	}

	if rf, ok := ret.Get(1).(func(*jwt.Token, models.Posting) error); ok {
		r1 = rf(token, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
